language: lisp
addons:
  postgresql: "9.3"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq sbcl
 - curl --no-progress-bar --retry 10 -o quicklisp.lisp -L http://beta.quicklisp.org/quicklisp.lisp
 - mysql -uroot -e 'GRANT ALL ON *.* TO nobody@"localhost" IDENTIFIED BY "nobody"'
 - mysql -e 'CREATE DATABASE `cl-dbi`'
 - psql -c 'create database "cl-dbi";' -U postgres
 - psql -c "CREATE USER nobody WITH PASSWORD 'nobody';" -U postgres

script:
 - sbcl --script t/run-test.lisp
